services:
  - type: web
    name: healhub-rasa
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python3 -m pip install --upgrade pip setuptools wheel packaging
      pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
