services:
  - type: web
    name: healhub-rasa
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python3 -m pip install --upgrade pip setuptools wheel packaging
      pip install -r requirements.txt
      rasa train
    startCommand: rasa run --enable-api --cors "*" --model models/20251023-171911-hot-arena.tar.gz --port 5005 --debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 5005
